### ISSUE TITLE
Wait for renderer and crashed

### ISSUE THREAD

**Issue by vishwajit76** [Doubleshotjs/doubleshot#1248]
> rimraf dist && vite

The CJS build of Vite's Node API is deprecated. See https://vite.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.

  VITE v5.4.11  ready in 1136 ms

  ➜  Local:   http://localhost:5000/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
DSB 💻 Mode:  Development 
DSB 💠 Application type:  electron 
DSB ✅ Prebuild succeeded! (85217.46ms)
DSB 🚦 Wait for renderer: http://localhost:5000/
E:\Github\electron-app\node_modules\wait-on\lib\wait-on.js:131
            return throwError(Error(`${TIMEOUT_ERR_MSG}: ${resourcesWaitingFor}`));
                              ^

Error: Timed out waiting for: http-get://localhost:5000/
rs\OperatorSubscriber.js:33:21)
    at Subscriber.next (E:\Github\electron-app\node_modules\rxjs\dist\cjs\internal\Subscriber.js:51:18)
    at AsyncAction.<anonymous> (E:\Github\electron-app\node_modules\rxjs\dist\cjs\internal\observable\timer.js:28:28)       
    at AsyncAction._execute (E:\Github\electron-app\node_modules\rxjs\dist\cjs\internal\scheduler\AsyncAction.js:79:18)     
    at AsyncAction.execute (E:\Github\electron-app\node_modules\rxjs\dist\cjs\internal\scheduler\AsyncAction.js:67:26)      
    at AsyncScheduler.flush (E:\Github\electron-app\node_modules\rxjs\dist\cjs\internal\scheduler\AsyncScheduler.js:38:33)  
    at listOnTimeout (node:internal/timers:569:17)

Node.js v18.20.5

**Comment by ArcherGu** [comment]
Hi, Can you provide a demo repository?

**Comment by vishwajit76** [comment]
https://github.com/ArcherGu/vite-react-nestjs-electron

**Comment by ArcherGu** [comment]
I tested this repo under node@18.20.5, but it didn't happen, my test system was win11 😢

**Comment by vishwajit76** [comment]
> I tested this repo under node@18.20.5, but it didn't happen, my test system was win11 😢

I delete and cloned again but same error occurred in demo and my project.

When i test vite render react project without VitePluginDoubleshot() plugin its run successfully but not run with Electron JS.

Logs:
```
PS E:\Github\vite-react-nestjs-electron> npm i
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: 'rimraf@6.0.1',
npm warn EBADENGINE   required: { node: '20 || >=22' },
npm warn EBADENGINE   current: { node: 'v18.20.5', npm: '10.8.2' }
npm warn EBADENGINE }
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: 'minimatch@10.0.1',
npm warn EBADENGINE   required: { node: '20 || >=22' },
npm warn EBADENGINE   current: { node: 'v18.20.5', npm: '10.8.2' }
npm warn EBADENGINE }
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: 'glob@11.0.0',
npm warn EBADENGINE   required: { node: '20 || >=22' },
npm warn EBADENGINE   current: { node: 'v18.20.5', npm: '10.8.2' }
npm warn EBADENGINE }
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: 'minimatch@10.0.1',
npm warn EBADENGINE   required: { node: '20 || >=22' },
npm warn EBADENGINE   current: { node: 'v18.20.5', npm: '10.8.2' }
npm warn EBADENGINE }
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: 'jackspeak@4.0.2',
npm warn EBADENGINE   required: { node: '20 || >=22' },
npm warn EBADENGINE   current: { node: 'v18.20.5', npm: '10.8.2' }
npm warn EBADENGINE }
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: 'minimatch@10.0.1',
npm warn EBADENGINE   required: { node: '20 || >=22' },
npm warn EBADENGINE   current: { node: 'v18.20.5', npm: '10.8.2' }
npm warn EBADENGINE }
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: 'path-scurry@2.0.0',
npm warn EBADENGINE   required: { node: '20 || >=22' },
npm warn EBADENGINE   current: { node: 'v18.20.5', npm: '10.8.2' }
npm warn EBADENGINE }
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: 'lru-cache@11.0.2',
npm warn EBADENGINE   required: { node: '20 || >=22' },
npm warn EBADENGINE   current: { node: 'v18.20.5', npm: '10.8.2' }
npm warn EBADENGINE }
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm warn deprecated npmlog@6.0.2: This package is no longer supported.
npm warn deprecated global-dirs@4.0.0: Renamed to global-directory
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
npm warn deprecated are-we-there-yet@3.0.1: This package is no longer supported.
npm warn deprecated boolean@3.2.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm warn deprecated gauge@4.0.4: This package is no longer supported.

> vite-react-nestjs-electron@0.0.1 postinstall
> electron-builder install-app-deps

  • electron-builder  version=25.1.8
  • executing @electron/rebuild  electronVersion=33.2.1 arch=x64 buildFromSource=false appDir=./
  • installing native dependencies  arch=x64
  • completed installing native dependencies

added 913 packages, and audited 914 packages in 2m

250 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS E:\Github\vite-react-nestjs-electron> npm run debug

> vite-react-nestjs-electron@0.0.1 debug
> rimraf dist && vite -- --dsb-debug

The CJS build of Vite's Node API is deprecated. See https://vite.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.

  VITE v6.0.3  ready in 896 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
DSB 💻 Mode:  DEBUG   Development 
DSB 💠 Application type:  electron 
DSB ✅ Prebuild succeeded! (14286.18ms)
DSB 🚦 Wait for renderer: http://localhost:5173/
E:\Github\vite-react-nestjs-electron\node_modules\wait-on\lib\wait-on.js:131
            return throwError(Error(`${TIMEOUT_ERR_MSG}: ${resourcesWaitingFor}`));
                              ^

Error: Timed out waiting for: http-get://localhost:5173/
    at E:\Github\vite-react-nestjs-electron\node_modules\wait-on\lib\wait-on.js:131:31
    at doInnerSub (E:\Github\vite-react-nestjs-electron\node_modules\rxjs\dist\cjs\internal\operators\mergeInternals.js:22:31)
    at outerNext (E:\Github\vite-react-nestjs-electron\node_modules\rxjs\dist\cjs\internal\operators\mergeInternals.js:17:70)
    at OperatorSubscriber._this._next (E:\Github\vite-react-nestjs-electron\node_modules\rxjs\dist\cjs\internal\operators\OperatorSubscriber.js:33:21)
    at Subscriber.next (E:\Github\vite-react-nestjs-electron\node_modules\rxjs\dist\cjs\internal\Subscriber.js:51:18)
    at AsyncAction.<anonymous> (E:\Github\vite-react-nestjs-electron\node_modules\rxjs\dist\cjs\internal\observable\timer.js:28:28)
    at AsyncAction._execute (E:\Github\vite-react-nestjs-electron\node_modules\rxjs\dist\cjs\internal\scheduler\AsyncAction.js:79:18)
    at AsyncAction.execute (E:\Github\vite-react-nestjs-electron\node_modules\rxjs\dist\cjs\internal\scheduler\AsyncAction.js:67:26)
    at AsyncScheduler.flush (E:\Github\vite-react-nestjs-electron\node_modules\rxjs\dist\cjs\internal\scheduler\AsyncScheduler.js:38:33)
    at listOnTimeout (node:internal/timers:569:17)

Node.js v18.20.5
```

**Comment by ArcherGu** [comment]
maybe you can try pnpm

**Comment by vishwajit76** [comment]
> maybe you can try pnpm

Okay, I will test with pnpm.

**Comment by vishwajit76** [comment]
Now its run with pnpm. Thanks

**Comment by vnvyvu** [comment]
I got same issue, but I dont want to use pnpm, just increase wait timeout by adding `waitTimeout: 60 * 1000` to `VitePluginDoubleshot` in `vite.config.mts`
